unified-font-object/ufoLib

- README.md
Clicking on the badges should open the CI project pages.
BTW the [AppVeyor project](https://ci.appveyor.com/project/unified-font-object/ufoLib) doesn’t seem to be enabled.
> README: link badges with Travis-CI and AppVeyor project pages

- Lib/ufoLib/__init__.py
basestring is (str, unicode) in Python2 and str in Python3.
> Python 2/3: replace str by basestring

- Lib/ufoLib/glifLib.py
- Lib/ufoLib/pointPen.py
- Lib/ufoLib/test/test_GLIF1.py
- Lib/ufoLib/test/test_GLIF2.py
- Lib/ufoLib/test/test_UFO1.py
- Lib/ufoLib/test/test_UFO2.py
- Lib/ufoLib/test/test_UFO3.py
I was hesitating to remove BasePointToSegmentPen and merge it all in PointToSegmentPen but maybe it's useful... I kept it here.
Also, in robofab there is a procedure that prints sample converted data in adapterPens.py and in the test suite there are tests that exercise pens but they use many pens, not all of which are in ufoLib. 
@anthrotype Would you write tests for this?
> pointPen: add adapter pens

- Lib/ufoLib/__init__.py
```python
Python 2.7.11 (default, Dec 16 2015, 11:56:37)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ufoLib import UFOWriter
>>> writer = UFOWriter('foo.ufo', structure='zip')
>>> writer.getGlyphSet()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/mnakamura/.ghq/github.com/mashabow/ufoLib/Lib/ufoLib/__init__.py", line 842, in getGlyphSet
return self._getGlyphSetFormatVersion3(layerName=layerName, defaultLayer=defaultLayer, glyphNameToFileNameFunc=glyphNameToFileNameFunc)
File "/Users/mnakamura/.ghq/github.com/mashabow/ufoLib/Lib/ufoLib/__init__.py", line 883, in _getGlyphSetFormatVersion3
return GlyphSet(path, fileSystem=self, …
```
> [ufo4] Fix _getGlyphSetFormatVersion3()

- Lib/ufoLib/glifLib.py
- Lib/ufoLib/plistFromETree.py
I'm getting a `FutureWarning` when running the latest ufoLib.
According to the [ElementTree docs](https://docs.python.org/3.5/library/xml.etree.elementtree.html):
> Caution: Elements with no subelements will test as False. This behavior will change in future versions. Use specific len(elem) or elem is None test instead.
> plistFromETree: use len(element) to check if there are subelements

- Lib/ufoLib/validators.py
The `collections` module provides a set of abstract base classes that can be used to test whether a class provides a particular interface (e.g. whether it is a mapping).
I believe it'd be better if ufoLib uses that with `isinstance` rather than requiring instances of `dict`, or subclasses of `dict`.
> validators: check isinstance of collections.Mapping rather than dict

- Lib/ufoLib/glifLib.py
When an element tree is built from code, or it is parsed from a string that was not pretty-printed (i.e. without indentation), the `text` attribute of an `Element` instance can be `None`.
Therefore, we must ensure it's not `None` before calling `strip()` method.
> glifLib: don't raise AttributeError if element.text attribute is None

- Lib/ufoLib/glifLib.py
the `layerinfo.plist` is an optional file. there's no reason why ufoLib has to write it all the time even when there's no `color` nor `lib` elements.
Currently the `lib` dict was being written all the time even if empty, and as a result a `layerinfo.plist` file is always generated, even if it does not contain any meaningful information.
> glifLib: don't write empty 'lib' element in layerinfo.plist

- .travis.yml
- Lib/ufoLib/__init__.py
- Lib/ufoLib/converters.py
- Lib/ufoLib/filenames.py
- Lib/ufoLib/glifLib.py
- MANIFEST.in
- appveyor.yml
- requirements.txt
- setup.cfg
- setup.py
- tox.ini
This PR enables running the test suite with [pytest](https://pytest.org), and also sets up the Travis and Appveyor CI to check the package installation and run the tests in isolated virtual environments using [Tox](https://tox.readthedocs.io/en/latest/).
It also prepares Travis for uploading distribution packages automatically upon tags, though the latter is commented-out as the authentication requires someone with push access to the repo
***
Since at least [December 2011](https://github.com/robofab-developers/robofab/commit/f9ec29518c13dfb8a83e040a13a96b47b759a011), robofab has had the version string in the setup.py frozen at `1.2`.
Its spin-off package, ufoLib has inherited the version after the separation, and has kept it like that even after the ufo3 branch was merged a few months ago …
> Set up CI to run pytest with tox; prepare auto-deployment

- requirements.txt
- setup.py
Now that a recent enough version of fonttools is available from PyPI, we can specify it in the setup.py `install_requires` key (so that it's resolved automatically with `pip install ufoLib`), as well as in the `requirements.txt` file.
For the setup.py, we allow any `"fonttools >= 3.1.2"`, so ufoLib can be installed with more recent versions of fonttools as well.
For the `requirements.txt` file, which we use to make our test environment, I fixed the version to `fonttools==3.1.2` (currently the latest one), as the test suite needs to run against explicitly specified requirements.
https://requires.io/ can be used to automate the updating of the requirements.txt, every time a new version of a dependency is published.
> specify fonttools 3.1.2 from PyPI in both setup.py and requirements.txt

- setup.py
The `url` field in setup.py must be the home page for the package.
I moved the url to the UFO spec in the 'long_description', so it will show up in the PyPI project page.
Checking for `import fontTools` is redundant since dependency resolution is now automatic.
> setup.py: point package url to github repo; remove `import fontTools` check

- Lib/ufoLib/pointPen.py
Fixes https://github.com/unified-font-object/ufoLib/issues/62
I wonder if we should add `**kwargs` to `beginPath` and `addComponent` as well.
`AbstractPointPen.addPoint` has that already, and `glifLib.GLIFPointPen` also has that for `beginPath` and `addComponent`. 
(btw, I hate tabs)
> [pointPen] add identifier=None argument to AbstractPointPen methods

- Lib/ufoLib/pointPen.py
The `beginPath` and `addPoint` methods of `PointToSegmentPen` already take extra `**kwargs` (via `BasePointToSegmentPen`); only the `addComponent` method does not.
This makes it raise `TypeError` when an unknown keyword argument is passed (e.g. 'identifier' for UFO3 objects).
For the `PointToSegmentPen`, which translates between the PointPen and the SegmentPen API, it is ok if we only use the arguments that have an equivalent in the SegmentPen API, and silently discard the extra `**kwargs`.
> [pointPen] make PointToSegmentPen.addComponent accept/ignore **kwargs

- Lib/ufoLib/pointPen.py
This is simply copy pasted from `defcon.pens.reverseContourPointPen`.
Fixes https://github.com/typesupply/defcon/issues/106
> [pointPen] add ReverseContourPointPen from defcon

- Lib/ufoLib/filesystem.py
```python
Python 2.7.13 (default, Jan  6 2017, 13:59:53)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ufoLib import UFOReader
>>> r = UFOReader('foo.ufoz')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/mnakamura/.ghq/github.com/mashabow/ufoLib/Lib/ufoLib/__init__.py", line 96, in __init__
self.fileSystem = FileSystem(path)
File "/Users/mnakamura/.ghq/github.com/mashabow/ufoLib/Lib/ufoLib/filesystem.py", line 78, in __init__
p for p in path.listdir("")
File "/Users/mnakamura/.pyenv/versions/ufoLib-2.7.13/lib/python2.7/site-packages/fs/zipfs.py", line 275, in listdir
return self._directory.listdir(path)
File …
```
> [filesystem] Fix error on opening zip in Python 2

- Lib/ufoLib/filesystem.py
With `fs.osfs.OSFS`, we have to specify [namespaces](https://pyfilesystem2.readthedocs.io/en/latest/info.html#namespaces) as `["details"]` to get the modification time.
```py
Python 3.6.2 (default, Aug 21 2017, 14:31:44)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ufoLib import UFOReader
>>> reader = UFOReader('foo.ufo')
>>> glyph_set = reader.getGlyphSet()
>>> glyph_set.readGlyph('a')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/mnakamura/.ghq/github.com/mashabow/ufoLib/Lib/ufoLib/glifLib.py", line 300, in readGlyph
text = self.getGLIF(glyphName)
File "/Users/mnakamura/.ghq/github.com/mashabow/ufoLib/Lib/ufoLib/glifLib.py", line 252, in getGLIF …
```
> [filesystem] Specify namespaces for getinfo()

- Lib/ufoLib/converters.py
> When converting kerning group names, remove the older '@MMK' prefixes

- .gitignore
- Lib/ufoLib/__init__.py
- Lib/ufoLib/glifLib.py
- Lib/ufoLib/test/test_GLIF2.py
- Lib/ufoLib/test/test_UFO1.py
- Lib/ufoLib/test/test_UFO2.py
- Lib/ufoLib/test/test_UFO3.py
- Lib/ufoLib/test/test_UFOConversion.py
- Lib/ufoLib/test/test_glifLib.py
A pass at making the validation optional for ufoLib. No speedup testing has been done with this yet. Read is set to have validation off by default, Write is set to have it on by default. One can turn on/off validation on each method as wanted, or just set the global class option and let it be.
There is one thing I couldn't untangle, the `_validateAndMassagePointStructures` method. It does things that are needed, and it does validation. Where one starts and the other ends, I wasn't 100% on, so I left this alone for now.
> Make validation optional

- Lib/ufoLib/glifLib.py
- Lib/ufoLib/test/test_GLIF1.py
- Lib/ufoLib/test/test_GLIF2.py
This is a regression from ufoLib v2.1.1, see
adobe-type-tools/afdko#462 (comment)
https://travis-ci.org/adobe-type-tools/afdko/jobs/401751859#L8427
when we were using the fonttools XMLWriter the xml declaration was always included. When using lxml with encoding="unicode" there is no default xml declaration.
https://lxml.de/parsing.html#python-unicode-strings
> add the default xml declaration in writeGlyphToString

- Lib/ufoLib/plistlib.py
- Lib/ufoLib/test/test_plistlib.py
Fixes #162 
This is True on python3, and False on python2 by default.
Can be set explicitly to obtain the same treatment for bytes vs data on both py2 and 3.
> add use_bultin_types option

- README.md
see #181
\+ archive the `unified-font-object/ufoLib` repository (to avoid confusion)
> adding note in README about move to fontTools.ufoLib
